"""
xlist settings
"""

USERS = {
      'vato' :'vato'
    , 'admin': 'admin'
}


CITIES_URL = 'http://www.craigslist.org/about/sites#{}'


CITY_URL = 'http://{}.craigslist.org/{}'


CACHE_DIRECTORY = './cache'


CATEGORIES = [
    { 'name':'community', 'url':'ccc', 'categories':[
        {'name':'activities', 'url':'act'},
        {'name':'artists', 'url':'ats'},
        {'name':'childcare', 'url':'kid'},
        {'name':'general', 'url':'com'},
        {'name':'groups', 'url':'grp'},
        {'name':'pets', 'url':'pet'},
        {'name':'events', 'url':'eve'},
        {'name':'lost+found', 'url':'laf'},
        {'name':'musicians', 'url':'muc'},
        {'name':'localnews', 'url':'vnn'},
        {'name':'politics', 'url':'pol'},
        {'name':'rideshare', 'url':'rid'},
        {'name':'volunteers', 'url':'vol'},
        {'name':'classes', 'url':'cls'}]},
    { 'name':'forums', 'url':'forums', 'categories':[
        {'name':'adopt', 'url':'/forums/?forumID=2232'},
        {'name':'apple', 'url':'/forums/?forumID=3232'},
        {'name':'arts', 'url':'/forums/?forumID=49'},
        {'name':'atheist', 'url':'/forums/?forumID=78'},
        {'name':'autos', 'url':'/forums/?forumID=5'},
        {'name':'beauty', 'url':'/forums/?forumID=88'},
        {'name':'bikes', 'url':'/forums/?forumID=95'},
        {'name':'celebs', 'url':'/forums/?forumID=47'},
        {'name':'comp', 'url':'/forums/?forumID=34'},
        {'name':'crafts', 'url':'/forums/?forumID=83'},
        {'name':'diet', 'url':'/forums/?forumID=122'},
        {'name':'divorce', 'url':'/forums/?forumID=76'},
        {'name':'dying', 'url':'/forums/?forumID=130'},
        {'name':'eco', 'url':'/forums/?forumID=99'},
        {'name':'educ', 'url':'/forums/?forumID=90'},
        {'name':'feedbk', 'url':'/forums/?forumID=8'},
        {'name':'film', 'url':'/forums/?forumID=41'},
        {'name':'fitness', 'url':'/forums/?forumID=92'},
        {'name':'fixit', 'url':'/forums/?forumID=64'},
        {'name':'food', 'url':'/forums/?forumID=22'},
        {'name':'frugal', 'url':'/forums/?forumID=2007'},
        {'name':'gaming', 'url':'/forums/?forumID=85'},
        {'name':'garden', 'url':'/forums/?forumID=54'},
        {'name':'haiku', 'url':'/forums/?forumID=575'},
        {'name':'health', 'url':'/forums/?forumID=43'},
        {'name':'help', 'url':'/forums/?forumID=9'},
        {'name':'history', 'url':'/forums/?forumID=81'},
        {'name':'housing', 'url':'/forums/?forumID=6'},
        {'name':'jobs', 'url':'/forums/?forumID=7'},
        {'name':'jokes', 'url':'/forums/?forumID=1257'},
        {'name':'kink', 'url':'/forums/?forumID=200269'},
        {'name':'legal', 'url':'/forums/?forumID=73'},
        {'name':'linux', 'url':'/forums/?forumID=1991'},
        {'name':'m4m', 'url':'/forums/?forumID=72'},
        {'name':'manners', 'url':'/forums/?forumID=79'},
        {'name':'marriage', 'url':'/forums/?forumID=1926'},
        {'name':'media', 'url':'/forums/?forumID=133'},
        {'name':'money', 'url':'/forums/?forumID=53'},
        {'name':'motocy', 'url':'/forums/?forumID=1947'},
        {'name':'music', 'url':'/forums/?forumID=24'},
        {'name':'nonprofit', 'url':'/forums/?forumID=501'},
        {'name':'open', 'url':'/forums/?forumID=4'},
        {'name':'outdoor', 'url':'/forums/?forumID=16'},
        {'name':'over 50', 'url':'/forums/?forumID=50'},
        {'name':'parent', 'url':'/forums/?forumID=39'},
        {'name':'pets', 'url':'/forums/?forumID=26'},
        {'name':'philos', 'url':'/forums/?forumID=71'},
        {'name':'photo', 'url':'/forums/?forumID=5500'},
        {'name':'p.o.c.', 'url':'/forums/?forumID=84'},
        {'name':'politics', 'url':'/forums/?forumID=20'},
        {'name':'psych', 'url':'/forums/?forumID=29'},
        {'name':'queer', 'url':'/forums/?forumID=46'},
        {'name':'recover', 'url':'/forums/?forumID=12'},
        {'name':'religion', 'url':'/forums/?forumID=59'},
        {'name':'romance', 'url':'/forums/?forumID=28'},
        {'name':'science', 'url':'/forums/?forumID=96'},
        {'name':'spirit', 'url':'/forums/?forumID=93'},
        {'name':'sports', 'url':'/forums/?forumID=32'},
        {'name':'tax', 'url':'/forums/?forumID=1040'},
        {'name':'travel', 'url':'/forums/?forumID=42'},
        {'name':'tv', 'url':'/forums/?forumID=98'},
        {'name':'vegan', 'url':'/forums/?forumID=2400'},
        {'name':'w4w', 'url':'/forums/?forumID=69'},
        {'name':'wed', 'url':'/forums/?forumID=15'},
        {'name':'wine', 'url':'/forums/?forumID=120'},
        {'name':'women', 'url':'/forums/?forumID=94'},
        {'name':'words', 'url':'/forums/?forumID=7000'},
        {'name':'writing', 'url':'/forums/?forumID=27'},
        {'name':'yoga', 'url':'/forums/?forumID=8620'}]},
    {'name':'housing', 'url':'hhh', 'categories':[
        {'name':'apts / housing', 'url':'apa/'},
        {'name':'rooms / shared', 'url':'roo/'},
        {'name':'sublets / temporary', 'url':'sub/'},
        {'name':'housing wanted', 'url':'hsw/'},
        {'name':'housing swap', 'url':'swp/'},
        {'name':'vacation rentals', 'url':'vac/'},
        {'name':'parking / storage', 'url':'prk/'},
        {'name':'office / commercial', 'url':'off/'},
        {'name':'real estate for sale', 'url':'rea/'}]},
    {'name':'for sale', 'url':'sss', 'categories':[
        {'name':'antiques', 'url':'ata/'},
        {'name':'baby+kid', 'url':'baa/'},
        {'name':'barter', 'url':'bar/'},
        {'name':'bikes', 'url':'bia/'},
        {'name':'boats', 'url':'boo/'},
        {'name':'books', 'url':'bka/'},
        {'name':'business', 'url':'bfa/'},
        {'name':'computer', 'url':'sya/'},
        {'name':'free', 'url':'zip/'},
        {'name':'furniture', 'url':'fua/'},
        {'name':'general', 'url':'foa/'},
        {'name':'household', 'url':'hsa/'},
        {'name':'jewelry', 'url':'jwa/'},
        {'name':'materials', 'url':'maa/'},
        {'name':'rvs+camp', 'url':'rva/'},
        {'name':'sporting', 'url':'sga/'},
        {'name':'tickets', 'url':'tia/'},
        {'name':'tools', 'url':'tla/'},
        {'name':'wanted', 'url':'waa/'},
        {'name':'appliances', 'url':'ppa/'},
        {'name':'arts+crafts', 'url':'ara/'},
        {'name':'atv/utv/sno', 'url':'sna/'},
        {'name':'auto parts', 'url':'pta/'},
        {'name':'beauty+hlth', 'url':'haa/'},
        {'name':'cars+trucks', 'url':'/i/autos'},
        {'name':'cds/dvd/vhs', 'url':'ema/'},
        {'name':'cell phones', 'url':'moa/'},
        {'name':'clothes+acc', 'url':'cla/'},
        {'name':'collectibles', 'url':'cba/'},
        {'name':'electronics', 'url':'ela/'},
        {'name':'farm+garden', 'url':'gra/'},
        {'name':'garage sale', 'url':'gms/'},
        {'name':'heavy equip', 'url':'hva/'},
        {'name':'motorcycles', 'url':'/i/motorcycles'},
        {'name':'music instr', 'url':'msa/'},
        {'name':'photo+video', 'url':'pha/'},
        {'name':'toys+games', 'url':'taa/'},
        {'name':'video gaming', 'url':'vga/'}]},
    { 'name':'services', 'url':'bbb', 'categories':[
        {'name':'beauty', 'url':'bts/'},
        {'name':'creative', 'url':'crs/'},
        {'name':'computer', 'url':'cps/'},
        {'name':'cycle', 'url':'cys/'},
        {'name':'event', 'url':'evs/'},
        {'name':'financial', 'url':'fns/'},
        {'name':'legal', 'url':'lgs/'},
        {'name':'lessons', 'url':'lss/'},
        {'name':'marine', 'url':'mas/'},
        {'name':'pet', 'url':'pas/'},
        {'name':'automotive', 'url':'aos/'},
        {'name':'farm+garden', 'url':'fgs/'},
        {'name':'household', 'url':'hss/'},
        {'name':'labor/move', 'url':'lbs/'},
        {'name':'skilld trade', 'url':'sks/'},
        {'name':'real estate', 'url':'rts/'},
        {'name':'sm biz ads', 'url':'biz/'},
        {'name':'therapeutic', 'url':'thp/'},
        {'name':'travel/vac', 'url':'trv/'},
        {'name':'write/ed/tr8', 'url':'wet/'}]},
    { 'name':'jobs', 'url':'jjj', 'categories':[
        {'name':'accounting+finance', 'url':'acc/'},
        {'name':'admin / office', 'url':'ofc/'},
        {'name':'arch / engineering', 'url':'egr/'},
        {'name':'art / media / design', 'url':'med/'},
        {'name':'biotech / science', 'url':'sci/'},
        {'name':'business / mgmt', 'url':'bus/'},
        {'name':'customer service', 'url':'csr/'},
        {'name':'education', 'url':'edu/'},
        {'name':'food / bev / hosp', 'url':'fbh/'},
        {'name':'general labor', 'url':'lab/'},
        {'name':'government', 'url':'gov/'},
        {'name':'human resources', 'url':'hum/'},
        {'name':'internet engineers', 'url':'eng/'},
        {'name':'legal  /  paralegal', 'url':'lgl/'},
        {'name':'manufacturing', 'url':'mnu/'},
        {'name':'marketing / pr / ad', 'url':'mar/'},
        {'name':'medical / health', 'url':'hea/'},
        {'name':'nonprofit sector', 'url':'npo/'},
        {'name':'real estate', 'url':'rej/'},
        {'name':'retail / wholesale', 'url':'ret/'},
        {'name':'sales / biz dev', 'url':'sls/'},
        {'name':'salon / spa / fitness', 'url':'spa/'},
        {'name':'security', 'url':'sec/'},
        {'name':'skilled trade / craft', 'url':'trd/'},
        {'name':'software / qa / dba', 'url':'sof/'},
        {'name':'systems / network', 'url':'sad/'},
        {'name':'technical support', 'url':'tch/'},
        {'name':'transport', 'url':'trp/'},
        {'name':'tv / film / video', 'url':'tfr/'},
        {'name':'web / info design', 'url':'web/'},
        {'name':'writing / editing', 'url':'wri/'},
        {'name':'[ETC]', 'url':'etc/'},
        {'name':'[ part-time ]', 'url':'/search/jjj?addFour=part-time'}]},
    { 'name':'gigs', 'url':'ggg', 'categories':[
        {'name':'crew', 'url':'cwg/'},
        {'name':'event', 'url':'evg/'},
        {'name':'labor', 'url':'lbg/'},
        {'name':'talent', 'url':'tlg/'},
        {'name':'computer', 'url':'cpg/'},
        {'name':'creative', 'url':'crg/'},
        {'name':'domestic', 'url':'dmg/'},
        {'name':'writing', 'url':'wrg/'}]}
]
